apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
  namespace: fcg-tech-fase-2
data:
  # Application Settings
  app-name: "Users API"
  app-version: "v1.0.0"
  
  # JWT Configuration
  jwt-issuer: "UsersAPI"
  jwt-audience: "TechChallengeApp"
  jwt-expiration: "60"
  
  # RabbitMQ Queues
  queue-user-created: "user.created"
  exchange-name: "users-exchange"
  
  # Logging
  log-level: "Information"
  
  # CORS (se necessário)
  cors-origins: "http://localhost:3000,http://localhost:5173"

  # MongoDB
  mongo-db: "users"
