apiVersion: v1
kind: Secret
metadata:
  name: users-secret
  namespace: fcg-tech-fase-2
type: Opaque
data:
  # Database Connection String (base64 encoded)
  # Host=postgres;Port=5432;Database=fcg_users_db;Username=fcg;Password=fcgpw
  connection-string: SG9zdD1wb3N0Z3JlcztQb3J0PTU0MzI7RGF0YWJhc2U9ZmNnX3VzZXJzX2RiO1VzZXJuYW1lPWZjZztQYXNzd29yZD1mY2dwdw==
  
  # JWT Secret (base64 encoded)
  # ChaveSuperSecretaCom32Caracteres!
  jwt-key: Q2hhdmVTdXBlclNlY3JldGFDb20zMkNhcmFjdGVyZXMh
  
  # Database Credentials (base64 encoded)
  db-username: ZmNn              # fcg
  db-password: ZmNncHc=          # fcgpw
