apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: fcg-tech-fase-4
  labels:
    app: users-api
spec:
  type: ClusterIP
  
  selector:
    app: users-api
  
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  
  sessionAffinity: None
