name: CI - Pull Request para Develop

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: usersapi
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      rabbitmq:
        image: rabbitmq:3.13-management
        env:
          RABBITMQ_DEFAULT_USER: ${{ secrets.RABBITMQ_USER }}
          RABBITMQ_DEFAULT_PASS: ${{ secrets.RABBITMQ_PASS }}
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5672:5672
          - 15672:15672

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore dependencies
        run: dotnet restore UsersAPI/UsersAPI.sln
      
      - name: Build
        run: dotnet build UsersAPI/UsersAPI.sln --configuration Release --no-restore
      
      - name: Run Tests
        run: dotnet test UsersAPI/UsersAPI.sln --configuration Release --no-build --verbosity normal
        env:
          ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Username=${{ secrets.DB_USER }};Password=${{ secrets.DB_PASSWORD }};Database=usersapi"
          RabbitMq__Host: localhost
          RabbitMq__Username: ${{ secrets.RABBITMQ_USER }}
          RabbitMq__Password: ${{ secrets.RABBITMQ_PASS }}
